apiVersion: v1
kind: LimitRange
metadata:
  name: pvc-limits
  namespace: app-ns # Specify the namespace where the LimitRange will be applied
spec:
  limits:
  - type: PersistentVolumeClaim
    min:
      storage: "5Gi"
    max:
      storage: "100Gi"
