apiVersion: v1
kind: LimitRange
metadata:
  name: pod-limits
  namespace: app-ns # Specify the namespace where the LimitRange will be applied
spec:
  limits:
  - type: Pod
    max:
      cpu: "4"
      memory: "4Gi"
    min:
      cpu: "500m"
      memory: "512Mi"
