apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: app-ns # Specify the namespace where the ResourceQuota will be applied
spec:
  hard:
    requests.cpu: "10" #  Total CPU requests allowed
    limits.cpu: "20" # Total CPU limits allowed
    requests.memory: "20Gi" # Total memory requests allowed
    limits.memory: "40Gi" # Total memory limits allowed
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: storage-quota
  namespace: app-ns # Specify the namespace where the ResourceQuota will be applied
spec:
  hard:
    persistentvolumeclaims: "10"
    requests.storage: "500Gi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-quota
  namespace: app-ns # Specify the namespace where the ResourceQuota will be applied
spec:
  hard:
    pods: "50"
    services: "20"
    configmaps: "100"
    secrets: "100"
